### ISSUE TITLE
How can i get useful email, password, and Android?

### ISSUE THREAD

**Issue by LMM0709** [jacksonchen/android-market-api#31]
When I run Main.java with my google account and Android Id="9774d56d682e549c"  there was an exception as below:
_com.gc.android.market.api.Tools$HttpException: HTTP Code 404 : https://developers.google.com/accounts/docs/AuthForInstalledApps
at com.gc.android.market.api.Tools.postUrl(Tools.java:66)
	at com.gc.android.market.api.MarketSession.login(MarketSession.java:139)
	at com.gc.android.market.api.MarketSession.login(MarketSession.java:126)
	at com.gc.android.market.api.Main.main(Main.java:33)_
My google account has signed in Google Play Store website. The Android Id="9774d56d682e549c" was searched from the google website. I don't have an Android phone so i did not sign in on an Android device.  Can you help me solve this problem which is the frist step for running this project. I have take two days to solve this problem but there is no progress.

I am a new user of java and android, i do not know what is the relationship between google account and Android id and how to get an Android id ? Am i need an android device ?

Thanks in advance
lmm

**Comment by jacksonchen** [comment]
Yes either that (get an Android device) or an Android emulator like genymotion

**Comment by LMM0709** [comment]
Hi jacksonchen, thanks in advance for your reply.

Before run this project am i need to the follow things:
1. Login my google account on an Android device or an Android emulator ?
2. Get an Android Id of the Android device or the Android emulator ?

Best Regards,
lmm

**Comment by jacksonchen** [comment]
Well you can use either an Android device or an Android emulator (or both if you want). Whichever you choose will have an associated Android ID attached to it that you use.
